// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADY1o9m4mld-p8UMi1bjIhSZFXtHxaIEw',
    appId: '1:181133610636:web:67a9bd10f12511d1dcb5a9',
    messagingSenderId: '181133610636',
    projectId: 'unlockway-9085f',
    authDomain: 'unlockway-9085f.firebaseapp.com',
    storageBucket: 'unlockway-9085f.appspot.com',
    measurementId: 'G-86GTHD241L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbAXRHZgOdFzRq69C2PSAwWnff0INA7G0',
    appId: '1:181133610636:android:f9dd3fdfaf964395dcb5a9',
    messagingSenderId: '181133610636',
    projectId: 'unlockway-9085f',
    storageBucket: 'unlockway-9085f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXLx5oKmXcWZHqeexPi77JeX_izkBYpnE',
    appId: '1:181133610636:ios:6d68961463b94f90dcb5a9',
    messagingSenderId: '181133610636',
    projectId: 'unlockway-9085f',
    storageBucket: 'unlockway-9085f.appspot.com',
    iosBundleId: 'com.example.unlockway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXLx5oKmXcWZHqeexPi77JeX_izkBYpnE',
    appId: '1:181133610636:ios:6d68961463b94f90dcb5a9',
    messagingSenderId: '181133610636',
    projectId: 'unlockway-9085f',
    storageBucket: 'unlockway-9085f.appspot.com',
    iosBundleId: 'com.example.unlockway',
  );
}
