// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEiv8S6b3GXlzK746_zxiF2xeUXXgLPG8',
    appId: '1:531448568433:web:c8a062a83553622c2e59d0',
    messagingSenderId: '531448568433',
    projectId: 'unlockwayapp',
    authDomain: 'unlockwayapp.firebaseapp.com',
    storageBucket: 'unlockwayapp.appspot.com',
    measurementId: 'G-EXY3CXLHD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvHgENG5xSM2II_iJOUTAbQGRXmKLczJM',
    appId: '1:531448568433:android:994df8ebc1f9fc292e59d0',
    messagingSenderId: '531448568433',
    projectId: 'unlockwayapp',
    storageBucket: 'unlockwayapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy79pFoJjT3B8FAn5AUckGbP0_XZAe7_s',
    appId: '1:531448568433:ios:0d41b727b82e55e42e59d0',
    messagingSenderId: '531448568433',
    projectId: 'unlockwayapp',
    storageBucket: 'unlockwayapp.appspot.com',
    iosClientId:
        '531448568433-p9o5sei06qqb27kvks7sefmpk7nhd51f.apps.googleusercontent.com',
    iosBundleId: 'com.example.unlockway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy79pFoJjT3B8FAn5AUckGbP0_XZAe7_s',
    appId: '1:531448568433:ios:0d41b727b82e55e42e59d0',
    messagingSenderId: '531448568433',
    projectId: 'unlockwayapp',
    storageBucket: 'unlockwayapp.appspot.com',
    iosClientId:
        '531448568433-p9o5sei06qqb27kvks7sefmpk7nhd51f.apps.googleusercontent.com',
    iosBundleId: 'com.example.unlockway',
  );
}
